### ISSUE TITLE
Homepage broken link

### ISSUE THREAD

**Issue by phi-line** [visgl/vis.gl#64]
The menu item `deck.gl` goes to `https://decl.gl` instead of `https://deck.gl`. I tried looking at `master`'s [links.yaml](https://github.com/visgl/vis.gl/blob/master/src/data/links.yaml), but I could not find anything that mentioned `decl`. Perhaps the website is out of date?

![image](https://user-images.githubusercontent.com/19956136/192391332-c319f7fd-5e4a-4aa2-a6bc-72c899ff4971.png)
![image](https://user-images.githubusercontent.com/19956136/192391472-1f11427a-57eb-40dd-964a-01da7147aac9.png)

**Comment by ilyabo** [comment]
This has been fixed by now
